spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: BestMentoringForStudents@gmail.com
    password: bestmentoringforstudents
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp
    test-connection: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mentoring
    username: root
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true